from .resume_prompts import (
    RESUME_GENERATION_PROMPT,
    RESUME_OPTIMIZATION_PROMPT,
    PROJECT_SUGGESTION_PROMPT,
)

__all__ = [
    "RESUME_GENERATION_PROMPT",
    "RESUME_OPTIMIZATION_PROMPT",
    "PROJECT_SUGGESTION_PROMPT",
]
